!------------------------------------------------------------------------
! The following more_chic_command are some chic commands for exotic purpose  
!------------------------------------------------------------------------
 SUBROUTINE more_chic_command_overall

 IMPLICIT NONE


 END SUBROUTINE more_chic_command_overall
!------------------------------------------------------------------------
!------------------------------------------------------------------------
! The following more_chic_command are some chic commands for exotic purpose  
!------------------------------------------------------------------------
 SUBROUTINE more_chic_command_afterall

 IMPLICIT NONE


 END SUBROUTINE more_chic_command_afterall
!------------------------------------------------------------------------
