# CMake generated Testfile for 
# Source directory: /home/pv/brg/code_fortran/compas_lmgc90/src/lmgc90_dev/examples/Pre/prepro_mesh2D/test_maillage_mixte
# Build directory: /home/pv/brg/code_fortran/compas_lmgc90/build_dev/examples/Pre/prepro_mesh2D/test_maillage_mixte
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Nn][Oo][Nn]_[Rr][Ee][Gg])$")
  add_test(Pre_mesh2D_test_maillage_mixte "/home/pv/brg/code_fortran/compas_lmgc90/src/lmgc90_dev/ci_scripts/run_test.sh" "/home/pv/anaconda3/envs/lmgc90/bin/python3.1" "Pre_mesh2D_test_maillage_mixte" "/home/pv/brg/code_fortran/compas_lmgc90/build_dev/examples/Pre/prepro_mesh2D/test_maillage_mixte/gen_sample.py" "/home/pv/brg/code_fortran/compas_lmgc90/build_dev/examples/Pre/prepro_mesh2D/test_maillage_mixte/command.py" "/examples/Pre/prepro_mesh2D/test_maillage_mixte")
  set_tests_properties(Pre_mesh2D_test_maillage_mixte PROPERTIES  ENVIRONMENT "PYTHONPATH=/home/pv/brg/code_fortran/compas_lmgc90/build_dev:/opt/intel/oneapi/advisor/2025.2/pythonapi:/opt/intel/oneapi/advisor/2025.2/pythonapi:/opt/intel/oneapi/advisor/2025.2/pythonapi" LABELS "quick" _BACKTRACE_TRIPLES "/home/pv/brg/code_fortran/compas_lmgc90/src/lmgc90_dev/ci_scripts/make_test.cmake;40;add_test;/home/pv/brg/code_fortran/compas_lmgc90/src/lmgc90_dev/examples/Pre/prepro_mesh2D/test_maillage_mixte/CMakeLists.txt;7;createTest;/home/pv/brg/code_fortran/compas_lmgc90/src/lmgc90_dev/examples/Pre/prepro_mesh2D/test_maillage_mixte/CMakeLists.txt;0;")
endif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Nn][Oo][Nn]_[Rr][Ee][Gg])$")
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Ss][Aa][Vv][Ee]_[Rr][Ee][Gg])$")
  add_test(save_Pre_mesh2D_test_maillage_mixte "/home/pv/brg/code_fortran/compas_lmgc90/src/lmgc90_dev/ci_scripts/save_test.sh" "/home/pv/anaconda3/envs/lmgc90/bin/python3.1" "Pre_mesh2D_test_maillage_mixte" "/home/pv/brg/code_fortran/compas_lmgc90/build_dev/examples/Pre/prepro_mesh2D/test_maillage_mixte/gen_sample.py" "/home/pv/brg/code_fortran/compas_lmgc90/build_dev/examples/Pre/prepro_mesh2D/test_maillage_mixte/command.py" "/examples/Pre/prepro_mesh2D/test_maillage_mixte")
  set_tests_properties(save_Pre_mesh2D_test_maillage_mixte PROPERTIES  ENVIRONMENT "PYTHONPATH=/home/pv/brg/code_fortran/compas_lmgc90/build_dev:/opt/intel/oneapi/advisor/2025.2/pythonapi:/opt/intel/oneapi/advisor/2025.2/pythonapi:/opt/intel/oneapi/advisor/2025.2/pythonapi" LABELS "quick" _BACKTRACE_TRIPLES "/home/pv/brg/code_fortran/compas_lmgc90/src/lmgc90_dev/ci_scripts/make_test.cmake;59;add_test;/home/pv/brg/code_fortran/compas_lmgc90/src/lmgc90_dev/examples/Pre/prepro_mesh2D/test_maillage_mixte/CMakeLists.txt;7;createTest;/home/pv/brg/code_fortran/compas_lmgc90/src/lmgc90_dev/examples/Pre/prepro_mesh2D/test_maillage_mixte/CMakeLists.txt;0;")
endif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Ss][Aa][Vv][Ee]_[Rr][Ee][Gg])$")
